# Generated by Django 5.1.3 on 2025-03-20 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('numero_identification', models.CharField(max_length=50, unique=True)),
                ('numero_assurance', models.CharField(max_length=50)),
                ('type_assurance', models.CharField(max_length=50)),
                ('numero_droit_taxi', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos_conducteurs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.gestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='AgentControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.gestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_fabrication', models.IntegerField()),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('couleur', models.CharField(max_length=50)),
                ('numero_chassis', models.CharField(max_length=50)),
                ('conducteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.conducteur')),
            ],
        ),
       
    ]
